name: kissim
channels:
  - conda-forge
  - defaults
dependencies:
    # Base depends
  - python>=3.6
  - pip
    # Package dependencies
  - biopandas
  - biopython 1.77
  - numpy
  - nglview
  - scipy
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab=2
  - ipywidgets>=7.5
  - tabulate
  # Testing
  # Workaround for https://github.com/computationalmodelling/nbval/issues/153
  - pytest 5.*
  - pytest-xdist
  - nbval
  - shyaml
  - pytest-cov
  - codecov
  # Docs
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  # Developement
  - black
  - pylint  
  # Remove when opencadd is conda-installable
  - rdkit
  - bravado
  - tqdm
  - pip:
    - black-nb
    - https://github.com/volkamerlab/opencadd/archive/master.zip
    - https://github.com/volkamerlab/kissim/archive/292e1a221ad640944d902a1d88531273df622818.zip
## For Jupyter lab extensions, run:
# conda install nodejs
# jupyter labextension install @jupyter-widgets/jupyterlab-manager nglview-js-widgets @jupyterlab/toc @ijmbarr/jupyterlab_spellchecker

