name: kissim
channels:
  - conda-forge
  - defaults
dependencies:
    # Base depends
  - python>=3.6
  - pip
    # Package dependencies
  - biopandas
  - biopython 1.77
  - numpy
  - nglview
  - scipy
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - ipywidgets>=7.5
  # Testing
  - pytest
  - pytest-cov
  - codecov
  # Docs
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  # Developement
  - black
  - pylint
  # Remove when opencadd is conda-installable
  - rdkit
  - bravado
  - tqdm
  - pip:
    - black-nb
    - https://github.com/volkamerlab/opencadd/archive/ac5e9816b835bcd757e1e33f2dcabe55b5ec7ef0.zip
    - https://github.com/volkamerlab/kissim/archive/b91153dfc7af51fbe9ad84be6daf8243f11bbdf3.zip
## For Jupyter lab extensions, run:
# conda install nodejs
# jupyter labextension install @jupyter-widgets/jupyterlab-manager nglview-js-widgets @jupyterlab/toc @ijmbarr/jupyterlab_spellchecker

