name: test
channels:
  - conda-forge
  - defaults
dependencies:
    # Base depends
  - python>=3.6
  - pip
  - openpyxl
  - tabulate
  - scikit-learn
  - opencadd
  - kissim
  # Testing
  # Workaround for https://github.com/computationalmodelling/nbval/issues/153
  - pytest 5.*
  - pytest-xdist
  - nbval
  - shyaml
  - pytest-cov
  - codecov
  # Docs
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  # Developement
  - black
  - pylint
  - pip:
    - black-nb
    - flake8-nb
    # the package itself (teachopencadd)
    - https://github.com/volkamerlab/kissim_app/archive/master.tar.gz

