name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  schedule:
    # Run a cron job once daily, weekdays only
    - cron: "0 3 1,15 * *"

jobs:
  test:
    name: Pytest
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - os: ubuntu-latest
            python-version: "3.6"
          - os: ubuntu-latest
            python-version: "3.7"
          - os: ubuntu-latest
            python-version: "3.8"
          - os: ubuntu-latest
            python-version: "3.9"
          - os: macos-latest
            python-version: "3.6"
          #- os: windows-latest
          #  python-version: "3.6"

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.cfg.python-version }}
          activate-environment: kissim
          channel-priority: true
          environment-file: environment.yaml
          auto-activate-base: false

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a
      - name: Environment information
        shell: bash -l {0}
        run: |
          conda info --all
          conda list
      - name: Unzip fingerprints 
        shell: bash -l {0}
        run: |
          unzip results/fingerprints.zip -d results
      - name: Unzip fingerprints (clean)
        shell: bash -l {0}
        run: |
          unzip results/fingerprints_clean.zip -d results
      - name: Run tests
        shell: bash -l {0}
        run: |
          PYTEST_ARGS="--nbval-lax --current-env --nbval-cell-timeout=900"
          pytest $PYTEST_ARGS
  format:
    name: Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install format dependencies
        run: python -m pip install black-nb shyaml
      - name: Run black-nb
        run: |
          black-nb -l 99 --check notebooks
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install lint dependencies
        shell: bash
        run: |
          python -m pip install flake8-nb
      - name: Run flake8-nb
        shell: bash
        run: |
          flake8-nb --config tox.ini notebooks
